# Check out https://docs.codemagic.io/yaml/yaml/ for more information
# Please review and update values in curly braces

workflows:
  ios-flutter:
    name: iOS App with Flutter Module
    environment:
      vars:
        FLUTTER_MODULE_DIR: "/home/med/AndroidStudioProjects/x_o/counter"
        HOST_IOS_APP_DIR: "/home/med/AndroidStudioProjects/x_o/counter"
        XCODE_PROJECT: "/home/med/AndroidStudioProjects/x_o/counter"
        XCODE_SCHEME: "/home/med/AndroidStudioProjects/x_o/counter"
      xcode: edge
      cocoapods: default
      flutter: stable
    scripts:
      - |
        # build Flutter module
        cd $FLUTTER_MODULE_DIR
        flutter packages get
        flutter build ios-framework --output=$FCI_BUILD_DIR/$HOST_IOS_APP_DIR/Flutter
      - |
        # build iOS project
        cd $HOST_IOS_APP_DIR
        pod install
        xcodebuild build -project "$XCODE_PROJECT.xcodeproj" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app